name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - run: sudo apt install lua5.3

    - name: Install Fennel
      run: |
        wget https://fennel-lang.org/downloads/fennel-1.5.1
        chmod +x fennel-1.5.1
        mv fennel-1.5.1 fennel

    - name: test
      run: |
        ./fennel tasks/build
        ./fennel tasks/run-tests
